name: Minidump document creation

on:
  push:
    branches: [ minidumpdoc ]
  pull_request:
    branches: [ minidumpdoc ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
           java-version: 1.8
      - name: Run Maven install
        run: mvn install

      - name: Run MinidumpDoc
        working-directory: ./dump
        run: mvn package exec:java -Dexec.mainClass=org.dbpedia.extraction.dump.util.MinidumpDoc

      - name: Updating test coverage table
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: 'Update with Github action'
          add: 'dump/src/test/resources/shaclTestsCoverageTable.md --force'